#obj-$(CONFIG_ARCH_DUMMY) += htc_8974-panel.o

obj-$(CONFIG_MACH_MEC_UL) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_DWG) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_TL) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_WHL) += htc_mec-panel.o
obj-$(CONFIG_MACH_A11_UL) += htc_a11-panel.o
